<a href="https://colab.research.google.com/github/PondKann/CXR-Project/blob/main/Data_Augmentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###### import

In [1]:
import os
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import cv2
import numpy as np
import pandas as pd
from torchsummary import summary
from skimage.io import imread, imsave
from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
# set the matplotlib backend so figures can be saved in the background
import matplotlib
matplotlib.use("Agg")

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.utils import to_categorical
from imutils import paths
import argparse

#### Load data

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
train_dir = '/content/drive/My Drive/Senior Project/xray_dataset_covid19/train'
validation_dir = '/content/drive/My Drive/Senior Project/xray_dataset_covid19/test'

In [5]:
train_normal_dir = os.path.join(train_dir,'NORMAL')
train_pneumonia_dir = os.path.join(train_dir,'PNEUMONIA')
validation_normal_dir = os.path.join(validation_dir,'NORMAL')
validation_pneumonia_dir = os.path.join(validation_dir,'PNEUMONIA')

train_pneumonia_dir

'/content/drive/My Drive/Senior Project/xray_dataset_covid19/train/PNEUMONIA'

#### สร้างตารางเก็บชื่อภาพ และโรค 2
ข้อมูลในไฟล์ train ทั้ง normal และ pneunomia มารวมอยู่ในไฟล์ all_train แล้วลองนำมาทำ data augment

In [14]:
train_normal_dir = os.path.join(train_dir,'NORMAL')
train_pneumonia_dir = os.path.join(train_dir,'PNEUMONIA')
train_ca_dir = os.path.join(train_dir,'CA')

In [15]:
all_train = '/content/drive/My Drive/Senior Project/xray_dataset_covid19/all_train'

สร้าง data dict ของรูป

In [16]:
normal = []
for i in range(len(os.listdir(train_normal_dir))):
    img = os.listdir(train_normal_dir)[i]
    normal.append(img)
tnormal = pd.DataFrame({'ImageName':[normal][0],
                                       'Type1': "Normal" ,
                                       'Type2': 0                      })

In [17]:
pneumonia = []
for i in range(len(os.listdir(train_pneumonia_dir))):
    img = os.listdir(train_pneumonia_dir)[i]
    pneumonia.append(img)
tpneumonia = pd.DataFrame({'ImageName':[pneumonia][0],
                                       'Type1': "Pneumonia" ,
                                       'Type2': 1                        })

In [18]:
tlungcanser = []
for i in range(len(os.listdir(train_ca_dir))):
    img = os.listdir(train_ca_dir)[i]
    tlungcanser.append(img)
tlungcanser = pd.DataFrame({'ImageName':[tlungcanser][0],
                                       'Type1': "Lungcanser" ,
                                       'Type2': 2                        })

In [19]:
data_train2 = pd.concat([tnormal, tpneumonia])
data_train2.head(3)

ImageName   Type1  Type2
0  IM-0006-0001.jpeg  Normal      0
1  IM-0003-0001.jpeg  Normal      0
2  IM-0001-0001.jpeg  Normal      0

In [20]:
data_train3 = pd.concat([tnormal, tpneumonia, tlungcanser])
data_train3.head(3)

ImageName   Type1  Type2
0  IM-0006-0001.jpeg  Normal      0
1  IM-0003-0001.jpeg  Normal      0
2  IM-0001-0001.jpeg  Normal      0

# 2 class
*   #1 output 1 มิติ  ความน่าจะเป็น นำมาแปลง 0,1
*   #2 output 2 มิติ  ความน่าจะเป็นที่จะเป็นคลาส 0 หรือ 1 



##แบ่งข้อมูล

In [22]:
train_img = []
for ImageName in tqdm(data_train2['ImageName']):               # รัน ชื่อรูป ในไฟล์ data_test2
    image_path = all_train +'/' + ImageName                       # ดึงรูปในโฟล์เดอร์มาทีละรูป
    img = cv2.imread(image_path)                                            # อ่านรูป
    img = cv2.resize(img, (224, 224))
    train_img.append(img)


100%|██████████| 148/148 [00:54<00:00,  2.72it/s]


In [23]:
data2 = np.array(train_img, dtype="float32") / 255.0

In [24]:
#1
labels2 = np.array(data_train2[['Type1']] )           #shape (148, 1) ค่าเป็น 0. กับ 1.  รัน model2.fit  ได้

len(labels2)
#labels.shape = (len(labels),)                          #เปลี่ยน dimention เป็น 1 มิติ 
labels2.shape

(148, 1)

In [25]:
le = LabelEncoder()                                                                   #จะแปลงชื่อ class เป็นตัวเลข
labels2 = le.fit_transform(labels2)                                                  # dimention ของ Y จะเป็น 1 (37,) ต้องเปลี่ยนเป็น (37,1) ก่อน ถึงจะรัน report ได้

labels2.shape = (len(labels2),1)
labels2.shape

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(148, 1)

In [26]:
le.classes_

array(['Normal', 'Pneumonia'], dtype=object)

In [27]:
(trainX, testX, trainY, testY) = train_test_split(data2, labels2,
	test_size=0.25, random_state=42)

In [28]:
trainX.ndim

4

## Data Augmentation  #1

### train

In [29]:
# initialize the initial learning rate, batch size, and number of
# epochs to train for
INIT_LR = 1e-1
BS = 8
EPOCHS = 50

In [30]:
# initialize an our data augmenter as an "empty" image data generator
aug = ImageDataGenerator()

In [31]:
aug = ImageDataGenerator(
		rotation_range=20,
		zoom_range=0.25,
		width_shift_range=0.25,
		height_shift_range=0.25,
		shear_range=0.25,
		horizontal_flip=True,
		fill_mode="nearest")

DenseNet201

In [32]:
base_model = tf.keras.applications.DenseNet201(input_shape=(224, 224, 3), include_top=False, weights="imagenet")

74850304/74836368 [==============================] - 1s 0us/step


In [33]:
base_model.trainable=False

#Add custom head
average_pooling_layer = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
prediction_layer = tf.keras.layers.Dense(units=1, activation="sigmoid")(average_pooling_layer)   #  unit = 1 คือ มิติของ output เป็น 1 มีค่าความน่าจะเป็นค่าเดียว
model = tf.keras.models.Model(inputs=base_model.input, outputs=prediction_layer)

In [34]:
model.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.0001), loss="binary_crossentropy", metrics=["accuracy"])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/rmsprop.py:130: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(RMSprop, self).__init__(name, **kwargs)


In [35]:
# train the network

H = model.fit(
	x=aug.flow(trainX, trainY, batch_size=BS),
	validation_data=(testX, testY),
	steps_per_epoch=len(trainX) // BS,
	epochs=5)

Epoch 1/5
13/13 [==============================] - 48s 3s/step - loss: 0.6826 - accuracy: 0.5865 - val_loss: 0.6518 - val_accuracy: 0.6216
Epoch 2/5
13/13 [==============================] - 32s 2s/step - loss: 0.6271 - accuracy: 0.6250 - val_loss: 0.6333 - val_accuracy: 0.6486
Epoch 3/5
13/13 [==============================] - 31s 2s/step - loss: 0.6675 - accuracy: 0.5728 - val_loss: 0.6084 - val_accuracy: 0.7297
Epoch 4/5
13/13 [==============================] - 32s 2s/step - loss: 0.6047 - accuracy: 0.7670 - val_loss: 0.5902 - val_accuracy: 0.7838
Epoch 5/5
13/13 [==============================] - 34s 3s/step - loss: 0.6120 - accuracy: 0.6893 - val_loss: 0.5723 - val_accuracy: 0.8378


### test

In [36]:
predictions = model.predict(testX, batch_size=BS)

In [59]:
predictions[:5]

array([[0.51462305],
       [0.36175758],
       [0.3816395 ],
       [0.44636542],
       [0.6624412 ]], dtype=float32)

In [37]:
predictions1 = []
for i in tqdm(predictions):
    if i > 0.5:
        predictions1.append(1)
    else:
        predictions1.append(0)
predictions1 = np.array(predictions1, dtype="float32")
predictions1.shape = (len(predictions1) ,1)                         #แปลงให้ predictions2 เป็น 2 มิติ
predictions1.ndim

100%|██████████| 37/37 [00:00<00:00, 82767.60it/s]


2

In [60]:
predictions1[:5]

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [38]:
predictions1.max(axis=1)

array([1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 1., 1.], dtype=float32)

In [39]:
testY.max(axis=1)

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1])

In [40]:
print(classification_report(testY.max(axis=1),	
                            predictions1.max(axis=1),  
							target_names=le.classes_ ))

              precision    recall  f1-score   support

      Normal       0.82      0.90      0.86        20
   Pneumonia       0.87      0.76      0.81        17

    accuracy                           0.84        37
   macro avg       0.84      0.83      0.83        37
weighted avg       0.84      0.84      0.84        37



## Data Augmentation  #2

In [ ]:
labels = np.array(data_train[['Type1']] )           #shape (148, 1) ค่าเป็น 0. กับ 1.  รัน model2.fit  ได้

In [ ]:
#2
le = LabelEncoder()                                                                   #จะแปลงชื่อ class เป็นตัวเลข
labels = le.fit_transform(labels)                                                  # dimention ของ Y จะเป็น 1 (37,) ต้องเปลี่ยนเป็น (37,1) ก่อน ถึงจะรัน report ได้
labels = to_categorical(labels, num_classes=2)                            # แปลงเป็นเลข ดัมมี่ (1เป็น 1,0 ----- 0 เป็น  0,1)    
            #shape (148, 2) ค่าเดิม 0. กับ 1.  หลังจากรันจะเป็น [0., 1.] กับ [1., 0.]  ------->  แต่จะรัน model2.fit ไม่ได้ อาจเพราะเป็นโมเดลสำหรับ output แค่ 1 ค่า 

(trainX, testX, trainY, testY) = train_test_split(data, labels,
	test_size=0.25, random_state=42)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### train

In [ ]:
# initialize the initial learning rate, batch size, and number of
# epochs to train for
INIT_LR = 1e-1
BS = 8
EPOCHS = 50

In [ ]:
# initialize an our data augmenter as an "empty" image data generator
aug = ImageDataGenerator()

In [ ]:
aug = ImageDataGenerator(
		rotation_range=20,
		zoom_range=0.25,
		width_shift_range=0.25,
		height_shift_range=0.25,
		shear_range=0.25,
		horizontal_flip=True,
		fill_mode="nearest")

DenseNet201

In [ ]:
base_model2 = tf.keras.applications.DenseNet201(input_shape=(224, 224, 3), include_top=False, weights="imagenet")

In [ ]:
base_model2.trainable=False

#Add custom head
average_pooling_layer = tf.keras.layers.GlobalAveragePooling2D()(base_model2.output)
prediction_layer = tf.keras.layers.Dense(units=2, activation="sigmoid")(average_pooling_layer)   # ลองแก้ unit จาก 1 เป็น 2
model2 = tf.keras.models.Model(inputs=base_model2.input, outputs=prediction_layer)

In [ ]:
model2.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.0001), loss="binary_crossentropy", metrics=["accuracy"])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/rmsprop.py:130: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(RMSprop, self).__init__(name, **kwargs)


In [ ]:
# train the network

H = model2.fit(
	x=aug.flow(trainX, trainY, batch_size=BS),
	validation_data=(testX, testY),
	steps_per_epoch=len(trainX) // BS,
	epochs=2)

Epoch 1/2
13/13 [==============================] - 32s 3s/step - loss: 0.7104 - accuracy: 0.5631 - val_loss: 0.6772 - val_accuracy: 0.6216
Epoch 2/2
13/13 [==============================] - 31s 2s/step - loss: 0.6581 - accuracy: 0.6311 - val_loss: 0.6596 - val_accuracy: 0.6216


### test

In [ ]:
predictions = model2.predict(testX, batch_size=BS)

In [ ]:
predictions.ndim

2

In [ ]:
predictions[:5]

array([[0.6088672 , 0.5897096 ],
       [0.5205667 , 0.66411275],
       [0.5682447 , 0.49947655],
       [0.5207887 , 0.58778536],
       [0.41414273, 0.4894217 ]], dtype=float32)

In [ ]:
print(classification_report(testY.max(axis=1),	
                            predictions.max(axis=1),  
							target_names=le.classes_ ))

ValueError: ignored

## Fine tune

In [ ]:
len(base_model2.layers)

707

In [ ]:
base_model2.trainable = True
for layer in base_model2.layers[:500]:    #fix w & bias in layer 0-500
    layer.trainable = False

In [ ]:
model2.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.0001),
              loss="binary_crossentropy", metrics=["accuracy"])

In [ ]:
#train
model2.fit_generator(train_generator, epochs=10, 
                    validation_data=valid_generator,
                    callbacks=[callback2])

# 3 class

##แบ่งข้อมูล

In [41]:
data_train3 = pd.concat([tnormal, tpneumonia, tlungcanser])
data_train3.head(3)

ImageName   Type1  Type2
0  IM-0006-0001.jpeg  Normal      0
1  IM-0003-0001.jpeg  Normal      0
2  IM-0001-0001.jpeg  Normal      0

In [ ]:
train_img3 = []
for ImageName in tqdm(data_train3['ImageName']):               # รัน ชื่อรูป ในไฟล์ data_test2
    image_path = all_train +'/' + ImageName                       # ดึงรูปในโฟล์เดอร์มาทีละรูป
    img = cv2.imread(image_path)                                            # อ่านรูป
    img = cv2.resize(img, (224, 224))
    train_img3.append(img)


## Data Augmentation 

In [43]:
data3 = np.array(train_img3, dtype="float32") / 255.0

In [44]:
labels3 = np.array(data_train3[['Type1']] )           #shape (180, 1) ค่าเป็น ชื่อคลาส

In [45]:
#2
le = LabelEncoder()                                                                   #จะแปลงชื่อ class เป็นตัวเลข
labels3 = le.fit_transform(labels3)                                                  # dimention ของ Y จะเป็น 1 (37,) ต้องเปลี่ยนเป็น (37,1) ก่อน ถึงจะรัน report ได้
labels3 = to_categorical(labels3, num_classes=3)                            # แปลงเป็นเลข ดัมมี่ (1เป็น 1,0 ----- 0 เป็น  0,1)    
            #shape (148, 2) ค่าเดิม 0. กับ 1.  หลังจากรันจะเป็น [0., 1.] กับ [1., 0.]  ------->  แต่จะรัน model2.fit ไม่ได้ อาจเพราะเป็นโมเดลสำหรับ output แค่ 1 ค่า 

(trainX, testX, trainY, testY) = train_test_split(data3, labels3,
	                                        test_size=0.25, random_state=42)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [46]:
le.classes_

array(['Lungcanser', 'Normal', 'Pneumonia'], dtype=object)

## train

In [47]:
# initialize the initial learning rate, batch size, and number of
# epochs to train for
INIT_LR = 1e-1
BS = 8
EPOCHS = 50

In [48]:
# initialize an our data augmenter as an "empty" image data generator
aug = ImageDataGenerator(
		rotation_range=20,
		zoom_range=0.25,
		width_shift_range=0.25,
		height_shift_range=0.25,
		shear_range=0.25,
		horizontal_flip=True,
		fill_mode="nearest")

DenseNet201

In [49]:
base_model3 = tf.keras.applications.DenseNet201(input_shape=(224, 224, 3), include_top=False, weights="imagenet")

In [50]:
base_model3.trainable=False

#Add custom head
average_pooling_layer = tf.keras.layers.GlobalAveragePooling2D()(base_model3.output)
prediction_layer = tf.keras.layers.Dense(units=3, activation="sigmoid")(average_pooling_layer)   # ลองแก้ unit จาก 1 เป็น 2
model3 = tf.keras.models.Model(inputs=base_model3.input, outputs=prediction_layer)

In [51]:
model3.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.0001), loss="binary_crossentropy", metrics=["accuracy"])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/rmsprop.py:130: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(RMSprop, self).__init__(name, **kwargs)


In [52]:
# train the network

H3 = model3.fit(
	x=aug.flow(trainX, trainY, batch_size=BS),
	validation_data=(testX, testY),
	steps_per_epoch=len(trainX) // BS,
	epochs=20)

Epoch 1/20
16/16 [==============================] - 60s 3s/step - loss: 0.7958 - accuracy: 0.2734 - val_loss: 0.7330 - val_accuracy: 0.2889
Epoch 2/20
16/16 [==============================] - 45s 3s/step - loss: 0.6985 - accuracy: 0.2598 - val_loss: 0.6749 - val_accuracy: 0.3111
Epoch 3/20
16/16 [==============================] - 46s 3s/step - loss: 0.6776 - accuracy: 0.2992 - val_loss: 0.6409 - val_accuracy: 0.3556
Epoch 4/20
16/16 [==============================] - 45s 3s/step - loss: 0.6485 - accuracy: 0.3228 - val_loss: 0.6114 - val_accuracy: 0.3556
Epoch 5/20
16/16 [==============================] - 46s 3s/step - loss: 0.6199 - accuracy: 0.3937 - val_loss: 0.5867 - val_accuracy: 0.4222
Epoch 6/20
16/16 [==============================] - 46s 3s/step - loss: 0.6105 - accuracy: 0.4882 - val_loss: 0.5681 - val_accuracy: 0.4444
Epoch 7/20
16/16 [==============================] - 45s 3s/step - loss: 0.6006 - accuracy: 0.4409 - val_loss: 0.5514 - val_accuracy: 0.4889
Epoch 8/20
16/16 [==

## test

In [53]:
predictions3 = model3.predict(testX, batch_size=BS)

In [54]:
predictions3.ndim

2

In [57]:
predictions3[:10]

array([[0.12724596, 0.56907374, 0.31893268],
       [0.07804206, 0.697567  , 0.15760434],
       [0.41863155, 0.41938156, 0.31549972],
       [0.15569252, 0.458377  , 0.45916003],
       [0.1579248 , 0.3835883 , 0.4520086 ],
       [0.14731026, 0.68557894, 0.41316867],
       [0.16871274, 0.73944485, 0.29132384],
       [0.13748863, 0.67382205, 0.3422739 ],
       [0.05129284, 0.11924973, 0.75081754],
       [0.18039489, 0.4803328 , 0.37958884]], dtype=float32)

In [61]:
print(classification_report(testY.argmax(axis=1),	
                           predictions3.argmax(axis=1),  
                            target_names=le.classes_))

              precision    recall  f1-score   support

  Lungcanser       1.00      0.83      0.91         6
      Normal       0.84      0.95      0.89        22
   Pneumonia       0.93      0.82      0.87        17

    accuracy                           0.89        45
   macro avg       0.92      0.87      0.89        45
weighted avg       0.90      0.89      0.89        45

